/*
 * Genesys Transfer Data
 * API for storing/retrieving transfer data.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

/**
* AnyOfTransferDataField
*/
public interface AnyOfTransferDataField {

}
